export const engConvert = {
  splashscreen: {
    splashText: 'Competition Commission of India',
    splashText1: 'Government of India',
    splashText2: 'Select Language',
    splashText3: 'Language can be changed later from the menu',
    splashText4: 'English',
    splashText5: 'Continue',
  },
  HomePage: {
    homepagetext: 'भारत सरकार',
    homepagetext1: 'Select Language',
    homepagetext2: 'English',
    homepagetext3: 'Hindi',
    homepagetext4: 'Cancel',
    homepagetext5: 'home',
    homepagetext6: 'Help',
    homepagetext7: 'Contact Us',
    homepagetext8: 'Quick Links',
    homepagetext9: 'Legal Framework',
    homepagetext10: 'Regulation of Combinations',
    homepagetext11: 'Institutional Framework',
    homepagetext12: 'Competition Economics',
    homepagetext13: 'Who We Are',
    homepagetext14: 'View all',
  },
  Munu_Quick_Links: {
    Info: 'About CCI',
    Target: 'Vision and Mission',
    Information: 'Information',

    Commission: 'The Commission',
    WhoisWho: 'Who is Who',
    Contact_Us: 'Contact Us',
    Organogram: 'Organogram',
  },
  LatestUpdatePage: {
    LatestUpdate: 'Latest Update',
  },
  CustomSidebarMenuPage: {
    legal_framwork: 'legal framwork',
    Antitrust: 'Antitrust',
    Combination: 'Combination',
    Competition_Economics: 'Competition Economics',
    Advocacy: 'Advocacy',
    International_Cooperation: 'International Cooperation',
    Capacity_Building: 'Capacity Building',
    Filing: 'Filing',
    Events: 'Events',
    Career: 'Career',
    Media_Gallery: 'Media Gallery',
    Library_Services: 'Library Services',
  },
};

export const hinConvert = {
  splashscreen: {
    splashText: 'भारतीय प्रतिस्पर्धा आयोग',
    splashText1: 'हिन्दी',
  },
  HomePage: {
    homepagetext: 'भारत सरकार',
    homepagetext1: 'भाषा चुने',
    homepagetext2: 'अंग्रेज़ी',
    homepagetext3: 'हिन्दी',
    homepagetext4: 'रद्द',
    homepagetext5: 'होम',
    homepagetext6: 'सहायता',
    homepagetext7: 'संपर्क',
    homepagetext8: 'लिंक',
    homepagetext9: 'विधिक ढांचा',
    homepagetext10: 'संयोजनों का विनियमन',
    homepagetext11: 'संस्थागत ढांचा',
    homepagetext12: 'प्रतिस्‍पर्धी अर्थनीति',
    homepagetext13: 'हम कौन हैं',
    homepagetext14: 'सभी को देखें',
  },
  Munu_Quick_Links: {
    Info: 'सीसीआई के बारे में',
    Target: 'विज़न और मिशन',
    Information: 'जानकारी',
    Commission: 'आयोग',
    WhoisWho: 'कौन क्‍या है',
    Contact_Us: 'हमसे संपर्क करें',
    Organogram: 'संगठन चार्ट',
  },
  LatestUpdatePage: {
    LatestUpdate: 'नवीनतम अपडेट',
  },
  CustomSidebarMenuPage: {
    legal_framwork: 'विधिक ढांचा',
    Antitrust: 'ट्रस्‍ट रोधी',
    Combination: 'संयोजन',
    Competition_Economics: 'प्रतिस्पर्धा अर्थशास्त्र',
    Advocacy: 'परामर्श',
    International_Cooperation: 'अंतराष्ट्रीय सहयोग',
    Capacity_Building: 'क्षमता निर्माण',
    Filing: 'फाइलिंग',
    Events: 'आयोजन',
    Career: 'करियर',
    Media_Gallery: 'मीडिया गैलरी',
    Library_Services: 'पुस्तकालय सेवाएं',
  },
};
