import { StyleSheet, Dimensions } from 'react-native';
import Colors from '../StyleFile/ColorFile.js';
import FontFamily from './Fontfamily.js';

const sliderWidth = Dimensions.get('window').width + 50;
const ITEM_WIDTH = Math.round(sliderWidth * 0.7);

export default StyleSheet.create({
  Main_Body: {
    flex: 1,
    backgroundColor: Colors.blue,
  },
  imageBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    height: 250,
  },
  p: {
    color: '#000000',
    fontSize: 14,
    fontFamily: FontFamily.fontFamily_500_value,
    textAlign: 'justify',
  },
  h6: {
    color: '#000000',
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: 'Poppins-Regular',
  },
  h3: {
    color: '#000000',
    fontFamily: FontFamily.fontFamily_800_value,
    fontSize: 20,
    marginBottom: 10,
  },
  h4: {
    color: '#000000',
    fontSize: 18,
    textAlign: 'justify',
    fontFamily: 'Poppins-Regular',
  },
  h1: {
    color: '#000000',
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: FontFamily.fontFamily_500_value,
  },
  br: {
    marginTop: 10,
  },
  h2: {
    color: '#000000',
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: FontFamily.fontFamily_500_value,
  },
  strong: {
    color: '#000000',
    fontSize: 16,
    textAlign: 'justify',
    marginBottom: 10,
    fontFamily: FontFamily.fontFamily_800_value,
  },
  img: { alignSelf: 'center', width: '50%', height: 200, margin: 20 },
  li: {
    color: '#000000',
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: FontFamily.fontFamily_800_value,
  },
  ul: {
    color: '#000000',
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: FontFamily.fontFamily_800_value,
  },

  div: {
    color: '#000000',
    fontSize: 15,
    textAlign: 'justify',
    fontFamily: FontFamily.fontFamily_500_value,
  },

  pageheading: {
    fontFamily: FontFamily.fontFamily_700_value,
    fontSize: 16,
    color: '#33ace6',
    marginLeft: 10,
  },

  table: {
    borderWidth: 1,
    borderColor: '#000',
    //borderCollapse: 'collapse',
    width: '100%',
  },
  th: {
    backgroundColor: '#f2f2f2',
    padding: 8,
    borderWidth: 1,
    borderColor: '#000',
  },
  td: {
    padding: 8,
    borderWidth: 1,
    borderColor: '#000',
  },
  tr: {
    flexDirection: 'row',
  },
  // table: {

  //   width: '100%',
  //   borderWidth: 1,
  //   borderColor: '#000',
  //   borderStyle: 'solid',
  //   borderCollapse: 'collapse',
  // },
  // tbody: {

  //   width: '100%',
  //   borderWidth: 1,
  //   borderColor: '#000',
  //   borderStyle: 'solid',
  //   borderCollapse: 'collapse',
  // },
  // tr: {
  //   flexDirection: 'row', // Use Flexbox for rows
  //   borderBottomWidth: 1,
  //   borderBottomColor: '#ddd',height: 100,
  // },
  // td: {
  //   borderWidth: 1,
  //   borderColor: '#000',
  //   //padding: 10,
  //   textAlign: 'center',
  //   // Set height and width based on the HTML content
  //   height: 82,
  //   width: '43.0987%', // Use percentage-based width similar to HTML
  //   backgroundColor: 'red', // Optional background color for the cell
  // },
  // th: { height: 200, // Set fixed height for this example
  //   //padding: 10, // Add padding for content separation
  //   borderWidth:1,
  //   borderColor: '#000', // Black borders for each cell
  //   borderStyle: 'solid',
  //   backgroundColor:'pink'},
  // td: { height: 90, borderWidth: 1, borderColor: '#000' },
  // tr: {  height: 90,borderWidth: 1, borderColor: '#000' },
  text: {
    color: '#000000',
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: FontFamily.fontFamily_500_value,
  },

  listcontent_60: {
    width: '70%',
    backgroundColor: Colors.white,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  listcontent_40_1: {
    width: '30%',
    backgroundColor: Colors.lightorangeColor,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  listcontent_40_2: {
    width: '30%',
    backgroundColor: Colors.lightblueColor,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  listcontent_heading: {
    fontFamily: FontFamily.fontFamily_300_value,
    fontSize: 15,
    color: Colors.black,
  },
  listcontent_value: {
    fontFamily: FontFamily.fontFamily_500_value,
    fontSize: 14,
    color: Colors.black,
    textAlign: 'left',
  },
  listcontent_valueView_Documents: {
    fontFamily: FontFamily.fontFamily_500_value,
    fontSize: 14,
    color: '#0058A0',
    textAlign: 'justify',
  },

  html_Documents_style: {
    selectable: true,
    style: {
      textAlign: 'left',
      fontFamily: FontFamily.fontFamily_600_value,
      fontSize: 16,
      color: '#000000',
    },
  },

  listcontent_heading_bold: {
    fontFamily: FontFamily.fontFamily_800_value,
    fontSize: 18,
    color: Colors.black,
    padding: 10,
  },
  listcontent_heading_bold1: {
    fontFamily: FontFamily.fontFamily_500_value,
    fontSize: 16,
    color: Colors.black,
    padding: 10,
    lineHeight: 18,
  },

  //cci style
  headerContainer: {
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 13,
    backgroundColor: '#064FB4',
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButton: {
    width: '15%',
    alignItems: 'center',
  },
  bottomHeader: {
    width: '100%',
    height: 70,
    flexDirection: 'row',
    borderTopStartRadius: 20,
    borderTopEndRadius: 20,
    borderTopWidth: 1,
    borderTopColor: '#E6E6E6',
  },
  headerTitle: {
    width: '45%',
    paddingLeft: 5,
  },
  titleText: {
    color: Colors.black,
    fontFamily: FontFamily.fontFamily_500_value,
    fontSize: 18,
  },
  headerActions: {
    width: '40%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingRight: 10,
    alignItems: 'center',
  },
  headerIcon: {
    width: 30,
    height: 30,
    tintColor: Colors.black,
  },
  actionIcon: {
    height: 22,
    width: 22,
    tintColor: Colors.black,
  },
  logoSection: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 10,
  },
  logoImage: {
    width: 50,
    height: 50,
    marginLeft: 10,
  },
  logoTextWrapper: {
    flex: 1,
    paddingLeft: 10,
    justifyContent: 'center',
  },
  splashText: {
    fontFamily: FontFamily.fontFamily_500_value,
    color: Colors.blueColor,
  },
  emblemImage: {
    width: 28,
    height: 50,
    marginRight: 10,
  },

  Silebarmenu_heading: {
    fontFamily: FontFamily.fontFamily_600_value,
    fontSize: 16,
    paddingHorizontal: 5,
    color: Colors.black,
  },
  Silebarmenu_heading1: {
    fontFamily: FontFamily.fontFamily_value,
    fontSize: 15,
    color: Colors.black,
  },
  contentContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#fff',
  },

  languageModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    //zIndex: 99,
  },

  languageModal: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    width: '80%',
    alignItems: 'center',
  },

  modalTitle: {
    fontSize: 18,
    fontFamily: FontFamily.fontFamily_500_value,
    marginBottom: 20,
  },

  languageOption: {
    paddingVertical: 10,
    width: '100%',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#ccc',
  },

  languageText: {
    fontSize: 16,
    color: Colors.black,
    fontFamily: FontFamily.fontFamily_300_value,
  },

  modalCloseBtn: {
    marginTop: 15,
  },
  closeText: {
    color: Colors.blueColor,
    fontFamily: FontFamily.fontFamily_500_value,
  },

  Select_Tab_style: {
    fontSize: 15,
    color: '#0058A0',
    fontFamily: FontFamily.fontFamily_600_value,
    paddingBottom: 5,
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  UnSelect_Tab_style: {
    fontSize: 15,
    color: '#000000',
    fontFamily: FontFamily.fontFamily_600_value,
    paddingBottom: 5,
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },

  inputStyle3: {
    flexDirection: 'row',
    marginTop: 10,
    height: 45,
    fontFamily: FontFamily.fontFamily_value,
    borderRadius: 5,
    borderColor: '#E6E6E6',
    borderWidth: 1,
    color: Colors.black,
    paddingLeft: 10,
  },
  inputStyle2: {
    paddingVertical: 7,
    paddingTop: 10,
    marginTop: 0,
    height: 45,
    paddingLeft: 13,
    fontFamily: FontFamily.fontFamily_value,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    borderColor: '#000000',
    borderWidth: 1,
    color: Colors.black,
  },
  inputStyle2_lable: {
    color: Colors.black,
    fontFamily: FontFamily.fontFamily_value,
    fontSize: 16,
    marginLeft: 5,
  },

  headerStyle_main: {
    backgroundColor: '#0A2C5E',
    height: Platform.OS === 'ios' ? 120 : 60,
  },
  headerStyle_main1: {
    backgroundColor: '#0463E7',
    flexDirection: 'row',
    width: '100%',
    marginTop: Platform.OS === 'ios' ? 50 : 30,
  },
  Searchboxderopdown_text: {
    flex: 1,
    fontSize: 15,
    color: Colors.black,
    padding: 5,
    fontFamily: FontFamily.fontFamily_500_value,
  },
  SelectDropdown_search_form: {
    height: 45,
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    borderColor: '#000000',
    borderWidth: 1,
  },
  buttonTextStyle123: {
    fontFamily: FontFamily.fontFamily_600_value,
    color: Colors.black,
    fontSize: 20,
    lineHeight: 28,
  },
  guestbutton: {
    flexDirection: 'row',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#e0e0e0',
    borderRadius: 18,
    borderWidth: 0,
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 0,
    flexDirection: 'column',
    height: '100%',
  },
  Image_center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  package_row_data: {
    flexDirection: 'row',
    backgroundColor: Colors.blue1,
    paddingBottom: 10,
  },
  row_data: {
    flexDirection: 'row',
    marginTop: 2,
    marginBottom: 2,
  },
  row_data1: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    marginLeft: 15,
    marginRight: 15,
    marginTop: 2,
    marginBottom: 2,
  },
  box_white: {
    borderRadius: 10,
    backgroundColor: '#ffffff',
    height: 50,
    borderColor: '#000000',
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -30,
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 20,
  },

  box_white_in_text: {
    fontSize: 16,
    fontFamily: FontFamily.fontFamily_value,
    color: Colors.blue,
  },
  circle_image: {
    width: 35,
    height: 35,
    borderRadius:
      Math.round(
        Dimensions.get('window').width + Dimensions.get('window').height,
      ) / 2,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  SectionStyle: {
    width: '100%',
    flexDirection: 'row',
    height: 45,
    marginTop: 5,
    marginLeft: 2,
    marginRight: 2,
    borderRadius: 5,
    borderColor: '#ffffff',
    borderBottomWidth: 1,
    alignItems: 'center',
    borderStyle: 'dashed',
  },
  inputtext: {
    width: '80%',
    height: 40,
    margin: 5,
    padding: 10,
  },

  SectionStyle2: {
    width: '90%',
    flexDirection: 'row',
    height: 45,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 10,
    borderRadius: 5,
    borderColor: '#000000',
    borderWidth: 1,
    alignItems: 'center',
  },
  SectionStyle3: {
    width: '100%',
    flexDirection: 'row',
    height: 45,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 10,
    borderRadius: 5,
    borderColor: '#000000',
    borderWidth: 1,
    alignItems: 'center',
  },
  Buttonstyle2: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    flexDirection: 'row',
    height: 40,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 10,
    backgroundColor: '#4166E9',
    alignItems: 'center',
  },

  pickerStyle: {
    width: '100%',
    height: 40,
    color: '#ffffff',
    fontSize: 25,
    fontFamily: FontFamily.fontFamily_value,
  },
  pickerStyle2: {
    width: '100%',
    height: 140,
    color: '#000000',
    fontSize: 25,
    fontFamily: FontFamily.fontFamily_value,
  },
  pickerStyle3: {
    width: '85%',
    height: 140,
    color: '#000000',
    fontSize: 15,

    fontFamily: FontFamily.fontFamily_value,
  },

  tabButtonselectstyle2: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    flexDirection: 'row',
    height: 45,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 8,
    backgroundColor: Colors.Button_color,
    alignItems: 'center',
  },
  tabButtonunselectstyle2: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    flexDirection: 'row',
    height: 45,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 8,
    backgroundColor: '#C9C9C9',
    alignItems: 'center',
  },
  tabtextselectstyle2: {
    fontSize: 16,
    fontFamily: FontFamily.fontFamily_700_value,
    color: '#000000',
  },
  tabtextunselectstyle2: {
    fontSize: 16,
    fontFamily: FontFamily.fontFamily_700_value,
    color: '#FFFFFF',
  },
  lable_text_gray: {
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.black,
    marginLeft: 15,
    marginTop: 10,
  },
  container: {
    backgroundColor: '#ffffff',
    flex: 1,
  },

  dropdown_homepage: {
    height: 45,
    width: '100%',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    backgroundColor: Colors.white,
    justifyContent: 'center',
    paddingHorizontal: 5,
  },

  row_Image: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 1,
  },
  SectionStyle123: {
    flexDirection: 'row',
    height: 40,
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: Colors.white,
    borderRadius: 10,
  },
  modelview_style: {
    flexDirection: 'row',
    backgroundColor: '#186BB9',
    height: 115,
    justifyContent: 'center',
    alignContent: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  menustyle_popup: {
    backgroundColor: '#ffffff',
    width: '70%',
    marginTop: 0,
    marginLeft: 0,
    marginRight: 100,
  },
  logouttext_style: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: FontFamily.fontFamily_value,
    marginLeft: 20,
    marginTop: 10,
    textTransform: 'uppercase',
  },
  footer_div2: {
    backgroundColor: 'black',
    fontFamily: 'Poppins-Black',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 32,
    marginTop: 0,
  },
  Footer_heading1: {
    color: 'white',
    fontFamily: FontFamily.fontFamily_value,
    fontSize: 10,
    marginLeft: 1,
    marginTop: 1,
    marginBottom: 1,
    fontWeight: 'bold',
  },
  usernametext_style: {
    color: '#ffffff',
    fontFamily: FontFamily.fontFamily_700_value,
    fontSize: 14,
    marginTop: 0,
    marginLeft: 20,
    textTransform: 'uppercase',
  },
  Menu_heading: {
    color: '#000000',
    fontFamily: FontFamily.fontFamily_value,
    fontSize: 12,
    marginLeft: 7,
    marginTop: 5,
    marginBottom: 5,
  },
  Card_name_style: {
    fontSize: 14,
    paddingLeft: 10,
    fontFamily: FontFamily.fontFamily_value,
    color: Colors.white,
  },
  Card_price_style: {
    fontSize: 14,
    fontFamily: FontFamily.fontFamily_600_value,
    color: Colors.white,
  },
  Card_style: {
    borderRadius: 10,
    flex: 1,
    width: ITEM_WIDTH,
    height: 167,
    justifyContent: 'center',
    marginLeft: -30,
  },
  Home_Heading: {
    fontSize: 17,
    color: '#000000',
    fontFamily: FontFamily.fontFamily_600_value,
  },
  Home_Heading_1: {
    color: 'white',
    fontSize: 18,
    marginTop: 20,
    marginLeft: 22,
    fontFamily: FontFamily.fontFamily_600_value,
  },
  Tab_Name_select_Heading: {
    fontSize: 12,
    color: Colors.white,
    fontFamily: FontFamily.fontFamily_value,
  },
  Tab_Name_unselect_Heading: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: FontFamily.fontFamily_value,
  },
  tabButtonunselectstyle4: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    height: 30,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
    alignItems: 'center',
    borderColor: '#fff',
    borderBottomWidth: 1,
  },
  tabButtonselectstyle4: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    height: 30,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
    alignItems: 'center',
    borderColor: '#0463E7',
    borderBottomWidth: 2,
  },
  tabtextselectstyle4: {
    fontSize: 14,
    fontFamily: FontFamily.fontFamily_value,
    color: '#0463E7',
    paddingLeft: 10,
    paddingRight: 10,
  },
  tabtextunselectstyle4: {
    fontSize: 14,
    fontFamily: FontFamily.fontFamily_value,
    color: '#fff',
    paddingLeft: 10,
    paddingRight: 10,
  },
  titleStyle: {
    color: Colors.black,
    fontSize: 20,
    fontFamily: FontFamily.fontFamily_700_value,
  },
  messageStyle: {
    color: Colors.black,
    fontSize: 16,
    fontFamily: FontFamily.fontFamily_value,
    textAlign: 'center',
  },
  textbox_labale_box: {
    justifyContent: 'center',
    marginLeft: 32,
    position: 'absolute',
    top: -2,
    zIndex: 99,
    display: 'none',
  },
  inputStyle2_form: {
    marginTop: 1,
    justifyContent: 'center',
    padding: 6,
    height: 42,
    paddingLeft: 10,
    fontSize: 15,
    fontFamily: FontFamily.fontFamily_value,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderColor: '#CFCFCF',
    borderWidth: 1,
    color: Colors.black,
    placeholderTextColor: Colors.black,
  },
  inputStyle2_form_icon: {
    marginLeft: 12,
    flexDirection: 'row',
    width: '92%',
    marginRight: 10,
    marginTop: 1,
    justifyContent: 'center',
    padding: 6,
    height: 42,
    paddingLeft: 10,
    fontSize: 15,
    fontFamily: FontFamily.fontFamily_value,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderColor: '#CFCFCF',
    borderWidth: 1,
    color: Colors.black,
    placeholderTextColor: Colors.black,
  },
  SelectDropdown_search: {
    margin: 15,
    height: 50,
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 5,
    padding: 12,
    shadowColor: '#000',
    borderColor: '#000000',
    borderWidth: 1,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  customSlide: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  customImage: {
    width: '100%',
    height: 200,
  },
  buttons: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    width: 10,
    height: 10,
    borderRadius: 10 * 2,
    backgroundColor: '#fff',
  },
  buttonSelected: {
    color: 'red',
    fontWeight: 'bold',
  },
});
